[rospy.client][INFO] 2021-01-16 08:51:53,756: init_node, name[/train_1903_1610787113726], pid[1903]
[xmlrpc][INFO] 2021-01-16 08:51:53,757: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-16 08:51:53,757: Started XML-RPC server [http://192.168.0.191:46539/]
[rospy.init][INFO] 2021-01-16 08:51:53,758: ROS Slave URI: [http://192.168.0.191:46539/]
[rospy.impl.masterslave][INFO] 2021-01-16 08:51:53,758: _ready: http://192.168.0.191:46539/
[rospy.registration][INFO] 2021-01-16 08:51:53,760: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-16 08:51:53,760: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-16 08:51:53,858: registered with master
[rospy.rosout][INFO] 2021-01-16 08:51:53,859: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-16 08:51:53,867: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-16 08:51:53,869: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-16 08:51:53,886: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:36903/], count 0
[rospy.internal][INFO] 2021-01-16 08:51:53,892: topic[/odom] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:51:53,897: topic[/start_goal_points] adding connection to [http://192.168.0.126:40949/], count 0
[rospy.internal][INFO] 2021-01-16 08:51:53,902: topic[/scan] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:51:53,905: topic[/scan] adding connection to [http://192.168.0.126:36669/], count 1
[rospy.internal][INFO] 2021-01-16 08:51:53,909: topic[/is_start_episode] adding connection to [http://192.168.0.126:34007/], count 0
[rospy.internal][INFO] 2021-01-16 08:51:54,057: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-16 08:51:54,061: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2021-01-16 08:51:54,156: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2021-01-16 08:51:56,417: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-16 08:51:56,421: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-16 08:51:56,421: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-16 08:51:56,421: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-16 08:51:56,422: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:36903/
[rospy.internal][INFO] 2021-01-16 08:51:56,422: topic[/odom] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 08:51:56,423: topic[/start_goal_points] removing connection to http://192.168.0.126:40949/
[rospy.internal][INFO] 2021-01-16 08:51:56,423: topic[/scan] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 08:51:56,424: topic[/scan] removing connection to http://192.168.0.126:36669/
[rospy.internal][INFO] 2021-01-16 08:51:56,425: topic[/is_start_episode] removing connection to http://192.168.0.126:34007/
[rospy.internal][WARNING] 2021-01-16 08:51:56,425: Unknown error initiating TCP/IP socket to 192.168.0.126:59449 (http://192.168.0.126:36903/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2021-01-16 08:51:56,425: atexit
[rospy.internal][WARNING] 2021-01-16 08:51:56,426: Unknown error initiating TCP/IP socket to 192.168.0.126:53085 (http://192.168.0.126:36669/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-16 08:51:56,427: Unknown error initiating TCP/IP socket to 192.168.0.126:57109 (http://192.168.0.126:34007/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

