[rospy.client][INFO] 2021-01-16 08:22:17,971: init_node, name[/train_1286_1610785337943], pid[1286]
[xmlrpc][INFO] 2021-01-16 08:22:17,972: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-16 08:22:17,972: Started XML-RPC server [http://192.168.0.191:45409/]
[rospy.init][INFO] 2021-01-16 08:22:17,973: ROS Slave URI: [http://192.168.0.191:45409/]
[rospy.impl.masterslave][INFO] 2021-01-16 08:22:17,973: _ready: http://192.168.0.191:45409/
[rospy.registration][INFO] 2021-01-16 08:22:17,974: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-16 08:22:17,975: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-16 08:22:18,073: registered with master
[rospy.rosout][INFO] 2021-01-16 08:22:18,073: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-16 08:22:18,080: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-16 08:22:18,082: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-16 08:22:18,098: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:36903/], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,103: topic[/odom] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,108: topic[/start_goal_points] adding connection to [http://192.168.0.126:40949/], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,115: topic[/scan] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,116: topic[/scan] adding connection to [http://192.168.0.126:36669/], count 1
[rospy.internal][INFO] 2021-01-16 08:22:18,120: topic[/is_start_episode] adding connection to [http://192.168.0.126:34007/], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,249: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,345: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-16 08:22:18,348: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2021-01-16 08:22:20,683: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-16 08:22:20,687: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-16 08:22:20,687: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-16 08:22:20,688: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-16 08:22:20,688: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:36903/
[rospy.internal][INFO] 2021-01-16 08:22:20,688: topic[/odom] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 08:22:20,689: topic[/start_goal_points] removing connection to http://192.168.0.126:40949/
[rospy.internal][INFO] 2021-01-16 08:22:20,689: topic[/scan] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 08:22:20,690: topic[/scan] removing connection to http://192.168.0.126:36669/
[rospy.internal][INFO] 2021-01-16 08:22:20,690: topic[/is_start_episode] removing connection to http://192.168.0.126:34007/
[rospy.impl.masterslave][INFO] 2021-01-16 08:22:20,691: atexit
[rospy.internal][WARNING] 2021-01-16 08:22:20,692: Unknown error initiating TCP/IP socket to 192.168.0.126:43067 (http://192.168.0.126:40949/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-16 08:22:20,693: Unknown error initiating TCP/IP socket to 192.168.0.126:53085 (http://192.168.0.126:36669/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-16 08:22:20,694: Unknown error initiating TCP/IP socket to 192.168.0.126:57109 (http://192.168.0.126:34007/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

