[rospy.client][INFO] 2020-12-26 05:45:13,585: init_node, name[/train_5168_1608961513558], pid[5168]
[xmlrpc][INFO] 2020-12-26 05:45:13,586: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-26 05:45:13,586: Started XML-RPC server [http://192.168.0.191:35373/]
[rospy.init][INFO] 2020-12-26 05:45:13,586: ROS Slave URI: [http://192.168.0.191:35373/]
[rospy.impl.masterslave][INFO] 2020-12-26 05:45:13,587: _ready: http://192.168.0.191:35373/
[rospy.registration][INFO] 2020-12-26 05:45:13,588: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-26 05:45:13,588: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-26 05:45:13,687: registered with master
[rospy.rosout][INFO] 2020-12-26 05:45:13,687: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-26 05:45:13,692: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-26 05:45:13,693: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-26 05:45:13,716: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:46063/], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,722: topic[/is_start_episode] adding connection to [http://192.168.0.201:42987/], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,725: topic[/scan] adding connection to [http://192.168.0.201:44479/], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,727: topic[/start_goal_points] adding connection to [http://192.168.0.201:40835/], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,729: topic[/scan] adding connection to [http://192.168.0.201:40197/], count 1
[rospy.internal][INFO] 2020-12-26 05:45:13,731: topic[/odom] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,880: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,881: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-12-26 05:45:13,979: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2020-12-26 05:46:00,472: Unknown error initiating TCP/IP socket to 192.168.0.201:33005 (http://192.168.0.201:46063/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-12-26 05:46:00,472: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:46063/
[rospy.internal][WARNING] 2020-12-26 05:46:00,490: Unknown error initiating TCP/IP socket to 192.168.0.201:44189 (http://192.168.0.201:44479/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-12-26 05:46:00,490: topic[/scan] removing connection to http://192.168.0.201:44479/
[rospy.core][INFO] 2020-12-26 05:46:03,531: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-12-26 05:46:03,537: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-26 05:46:03,538: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-26 05:46:03,538: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-26 05:46:03,538: topic[/odom] removing connection to http://192.168.0.201:40197/
[rospy.internal][INFO] 2020-12-26 05:46:03,539: topic[/start_goal_points] removing connection to http://192.168.0.201:40835/
[rospy.internal][WARNING] 2020-12-26 05:46:03,539: Unknown error initiating TCP/IP socket to 192.168.0.201:56385 (http://192.168.0.201:40197/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-26 05:46:03,540: topic[/scan] removing connection to http://192.168.0.201:40197/
[rospy.internal][WARNING] 2020-12-26 05:46:03,541: Unknown error initiating TCP/IP socket to 192.168.0.201:56385 (http://192.168.0.201:40197/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-26 05:46:03,541: topic[/is_start_episode] removing connection to http://192.168.0.201:42987/
[rospy.impl.masterslave][INFO] 2020-12-26 05:46:03,541: signal-2
[rospy.internal][WARNING] 2020-12-26 05:46:03,542: Unknown error initiating TCP/IP socket to 192.168.0.201:59769 (http://192.168.0.201:42987/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-12-26 05:46:04,028: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,058: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,091: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,122: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,168: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,187: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,220: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-12-26 05:46:04,229: signal_shutdown [atexit]
