[rospy.client][INFO] 2020-12-23 10:07:46,567: init_node, name[/train_2277_1608718066537], pid[2277]
[xmlrpc][INFO] 2020-12-23 10:07:46,568: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-23 10:07:46,569: Started XML-RPC server [http://192.168.0.191:45757/]
[rospy.init][INFO] 2020-12-23 10:07:46,569: ROS Slave URI: [http://192.168.0.191:45757/]
[rospy.impl.masterslave][INFO] 2020-12-23 10:07:46,569: _ready: http://192.168.0.191:45757/
[rospy.registration][INFO] 2020-12-23 10:07:46,571: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-23 10:07:46,571: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-23 10:07:46,670: registered with master
[rospy.rosout][INFO] 2020-12-23 10:07:46,670: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-23 10:07:46,675: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-23 10:07:46,677: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-23 10:07:46,692: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:38273/], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,699: topic[/scan] adding connection to [http://192.168.0.201:41653/], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,700: topic[/scan] adding connection to [http://192.168.0.201:39961/], count 1
[rosout][ERROR] 2020-12-23 10:07:46,704: bad callback: <bound method ROSNode.temporal_bev_image_callback of <__main__.ROSNode object at 0x7f4b5e8f6250>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 111, in temporal_bev_image_callback
    cv_temporal_bev_image = self.bridge.imgmsg_to_cv2(msg, desired_encoding='passthrough')
AttributeError: 'ROSNode' object has no attribute 'bridge'

[rospy.internal][INFO] 2020-12-23 10:07:46,711: topic[/start_goal_points] adding connection to [http://192.168.0.201:33305/], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,714: topic[/is_start_episode] adding connection to [http://192.168.0.201:38289/], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,718: topic[/odom] adding connection to [http://192.168.0.201:39961/], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,886: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,887: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-23 10:07:46,888: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2020-12-23 10:07:49,005: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-23 10:07:49,009: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-23 10:07:49,009: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-23 10:07:49,009: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-23 10:07:49,010: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:38273/
[rospy.internal][INFO] 2020-12-23 10:07:49,010: topic[/odom] removing connection to http://192.168.0.201:39961/
[rospy.internal][INFO] 2020-12-23 10:07:49,010: topic[/start_goal_points] removing connection to http://192.168.0.201:33305/
[rospy.internal][INFO] 2020-12-23 10:07:49,011: topic[/scan] removing connection to http://192.168.0.201:41653/
[rospy.internal][INFO] 2020-12-23 10:07:49,011: topic[/scan] removing connection to http://192.168.0.201:39961/
[rospy.internal][INFO] 2020-12-23 10:07:49,011: topic[/is_start_episode] removing connection to http://192.168.0.201:38289/
[rospy.impl.masterslave][INFO] 2020-12-23 10:07:49,011: atexit
[rospy.internal][WARNING] 2020-12-23 10:07:49,012: Unknown error initiating TCP/IP socket to 192.168.0.201:50065 (http://192.168.0.201:38273/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-23 10:07:49,013: Unknown error initiating TCP/IP socket to 192.168.0.201:53267 (http://192.168.0.201:41653/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

