[rospy.client][INFO] 2020-12-26 05:15:21,972: init_node, name[/train_4111_1608959721941], pid[4111]
[xmlrpc][INFO] 2020-12-26 05:15:21,973: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-26 05:15:21,974: Started XML-RPC server [http://192.168.0.191:40123/]
[rospy.init][INFO] 2020-12-26 05:15:21,974: ROS Slave URI: [http://192.168.0.191:40123/]
[rospy.impl.masterslave][INFO] 2020-12-26 05:15:21,974: _ready: http://192.168.0.191:40123/
[rospy.registration][INFO] 2020-12-26 05:15:21,976: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-26 05:15:21,976: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-26 05:15:22,075: registered with master
[rospy.rosout][INFO] 2020-12-26 05:15:22,075: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-26 05:15:22,081: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-26 05:15:22,082: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-26 05:15:22,109: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:33411/], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,114: topic[/scan] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,115: topic[/is_start_episode] adding connection to [http://192.168.0.201:42987/], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,117: topic[/scan] adding connection to [http://192.168.0.201:46427/], count 1
[rospy.internal][INFO] 2020-12-26 05:15:22,120: topic[/start_goal_points] adding connection to [http://192.168.0.201:40835/], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,122: topic[/odom] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,281: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,282: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-12-26 05:15:22,287: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-12-26 05:15:24,392: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-26 05:15:24,396: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-26 05:15:24,396: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-26 05:15:24,396: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-26 05:15:24,397: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:33411/
[rospy.internal][INFO] 2020-12-26 05:15:24,397: topic[/odom] removing connection to http://192.168.0.201:40197/
[rospy.internal][INFO] 2020-12-26 05:15:24,397: topic[/start_goal_points] removing connection to http://192.168.0.201:40835/
[rospy.internal][INFO] 2020-12-26 05:15:24,398: topic[/scan] removing connection to http://192.168.0.201:40197/
[rospy.internal][INFO] 2020-12-26 05:15:24,398: topic[/scan] removing connection to http://192.168.0.201:46427/
[rospy.internal][INFO] 2020-12-26 05:15:24,398: topic[/is_start_episode] removing connection to http://192.168.0.201:42987/
[rospy.impl.masterslave][INFO] 2020-12-26 05:15:24,399: atexit
[rospy.internal][WARNING] 2020-12-26 05:15:24,399: Unknown error initiating TCP/IP socket to 192.168.0.201:42523 (http://192.168.0.201:40835/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-26 05:15:24,400: Unknown error initiating TCP/IP socket to 192.168.0.201:56385 (http://192.168.0.201:40197/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-26 05:15:24,401: Unknown error initiating TCP/IP socket to 192.168.0.201:34085 (http://192.168.0.201:46427/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

