[rospy.client][INFO] 2021-01-18 08:43:29,109: init_node, name[/train_4663_1610959409080], pid[4663]
[xmlrpc][INFO] 2021-01-18 08:43:29,110: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-18 08:43:29,111: Started XML-RPC server [http://192.168.0.191:32951/]
[rospy.init][INFO] 2021-01-18 08:43:29,111: ROS Slave URI: [http://192.168.0.191:32951/]
[rospy.impl.masterslave][INFO] 2021-01-18 08:43:29,111: _ready: http://192.168.0.191:32951/
[rospy.registration][INFO] 2021-01-18 08:43:29,113: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-18 08:43:29,113: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-18 08:43:29,211: registered with master
[rospy.rosout][INFO] 2021-01-18 08:43:29,212: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-18 08:43:29,219: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-18 08:43:29,221: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-18 08:43:29,239: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:34427/], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,245: topic[/odom] adding connection to [http://192.168.0.126:44411/], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,249: topic[/start_goal_points] adding connection to [http://192.168.0.126:40887/], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,257: topic[/scan] adding connection to [http://192.168.0.126:44411/], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,258: topic[/scan] adding connection to [http://192.168.0.126:46009/], count 1
[rospy.internal][INFO] 2021-01-18 08:43:29,263: topic[/is_start_episode] adding connection to [http://192.168.0.126:40755/], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,490: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,491: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-18 08:43:29,492: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2021-01-18 08:43:31,751: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-18 08:43:31,755: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-18 08:43:31,755: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-18 08:43:31,755: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-18 08:43:31,756: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:34427/
[rospy.internal][INFO] 2021-01-18 08:43:31,756: topic[/odom] removing connection to http://192.168.0.126:44411/
[rospy.internal][INFO] 2021-01-18 08:43:31,757: topic[/start_goal_points] removing connection to http://192.168.0.126:40887/
[rospy.internal][INFO] 2021-01-18 08:43:31,757: topic[/scan] removing connection to http://192.168.0.126:44411/
[rospy.internal][INFO] 2021-01-18 08:43:31,758: topic[/scan] removing connection to http://192.168.0.126:46009/
[rospy.internal][WARNING] 2021-01-18 08:43:31,759: Unknown error initiating TCP/IP socket to 192.168.0.126:49689 (http://192.168.0.126:34427/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2021-01-18 08:43:31,759: topic[/is_start_episode] removing connection to http://192.168.0.126:40755/
[rospy.impl.masterslave][INFO] 2021-01-18 08:43:31,759: atexit
[rospy.internal][WARNING] 2021-01-18 08:43:31,760: Unknown error initiating TCP/IP socket to 192.168.0.126:43043 (http://192.168.0.126:44411/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-18 08:43:31,761: Unknown error initiating TCP/IP socket to 192.168.0.126:36803 (http://192.168.0.126:46009/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-18 08:43:31,761: Unknown error initiating TCP/IP socket to 192.168.0.126:50861 (http://192.168.0.126:40755/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-18 08:43:31,762: Unknown error initiating TCP/IP socket to 192.168.0.126:51919 (http://192.168.0.126:40887/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

