[rospy.client][INFO] 2021-01-09 03:51:15,559: init_node, name[/train_3038_1610164275545], pid[3038]
[xmlrpc][INFO] 2021-01-09 03:51:15,560: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-09 03:51:15,560: Started XML-RPC server [http://192.168.0.162:45617/]
[rospy.init][INFO] 2021-01-09 03:51:15,560: ROS Slave URI: [http://192.168.0.162:45617/]
[rospy.impl.masterslave][INFO] 2021-01-09 03:51:15,560: _ready: http://192.168.0.162:45617/
[rospy.registration][INFO] 2021-01-09 03:51:15,560: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2021-01-09 03:51:15,560: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-09 03:51:15,660: registered with master
[rospy.rosout][INFO] 2021-01-09 03:51:15,660: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-09 03:51:15,663: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-09 03:51:15,664: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-09 03:51:15,680: topic[/is_start_episode] adding connection to [http://192.168.0.201:45929/], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,680: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:36961/], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,682: topic[/scan] adding connection to [http://192.168.0.201:34577/], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,682: topic[/scan] adding connection to [http://192.168.0.201:41063/], count 1
[rospy.internal][INFO] 2021-01-09 03:51:15,683: topic[/start_goal_points] adding connection to [http://192.168.0.201:42155/], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,683: topic[/odom] adding connection to [http://192.168.0.201:34577/], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,881: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,884: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2021-01-09 03:51:15,885: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2021-01-09 03:54:40,464: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-01-09 03:54:40,469: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-09 03:54:40,469: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-09 03:54:40,470: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-09 03:54:40,470: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:36961/
[rospy.internal][INFO] 2021-01-09 03:54:40,470: topic[/odom] removing connection to http://192.168.0.201:34577/
[rospy.internal][WARNING] 2021-01-09 03:54:40,471: Unknown error initiating TCP/IP socket to 192.168.0.201:40733 (http://192.168.0.201:36961/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2021-01-09 03:54:40,472: topic[/start_goal_points] removing connection to http://192.168.0.201:42155/
[rospy.internal][WARNING] 2021-01-09 03:54:40,472: Unknown error initiating TCP/IP socket to 192.168.0.201:47923 (http://192.168.0.201:34577/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2021-01-09 03:54:40,473: topic[/scan] removing connection to http://192.168.0.201:34577/
[rospy.internal][WARNING] 2021-01-09 03:54:40,473: Unknown error initiating TCP/IP socket to 192.168.0.201:46057 (http://192.168.0.201:42155/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
OSError: [Errno 9] Bad file descriptor

[rospy.internal][INFO] 2021-01-09 03:54:40,473: topic[/scan] removing connection to http://192.168.0.201:41063/
[rospy.internal][WARNING] 2021-01-09 03:54:40,474: Unknown error initiating TCP/IP socket to 192.168.0.201:47923 (http://192.168.0.201:34577/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-09 03:54:40,474: Unknown error initiating TCP/IP socket to 192.168.0.201:53761 (http://192.168.0.201:41063/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2021-01-09 03:54:40,475: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2021-01-09 03:54:40,475: topic[/is_start_episode] removing connection to http://192.168.0.201:45929/
[rospy.impl.masterslave][INFO] 2021-01-09 03:54:40,476: signal-2
[rospy.core][INFO] 2021-01-09 03:54:40,592: signal_shutdown [signal-2]
[rospy.core][INFO] 2021-01-09 03:54:41,146: signal_shutdown [atexit]
